export const LOGIN = 'LOGIN';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const GET_USER_INFO = 'GET_USER_INFO';
export const FETCHED_USER_INFO = 'FETCHED_USER_INFO';

export const GET_USER_PUBLICATIONS = 'GET_USER_PUBLICATIONS';
export const FETCHING_USER_PUBLICATIONS = 'FETCHING_USER_PUBLICATIONS';
export const FETCHED_USER_PUBLICATIONS = 'FETCHED_USER_PUBLICATIONS';
export const NO_MORE_USER_PUBLICATIONS = 'NO_MORE_USER_PUBLICATIONS';
export const CLEAR_USER_PUBLICATIONS = 'CLEAR_USER_PUBLICATIONS';

export const GET_WORK_TYPES = 'GET_WORK_TYPES';
export const FETCHED_WORK_TYPES = 'FETCHED_WORK_TYPES';

export const GET_ACCESS_TYPES = 'GET_ACCESS_TYPES';
export const FETCHED_ACCESS_TYPES = 'FETCHED_ACCESS_TYPES';

export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const FETCHED_USER_FOLLOWERS = 'FETCHED_USER_FOLLOWERS';

export const GET_PARTNERS = 'GET_PARTNERS';
export const FETCHED_USER_PARTNERS = 'FETCHED_USER_PARTNERS';

export const PROMOTE_PUBLICATION = 'PROMOTE_PUBLICATION';
export const LIKE_PUBLICATION = 'LIKE_PUBLICATION';
export const POST_PUBLICATION = 'POST_PUBLICATION';

export const ERROR_OCCUR = 'ERROR_OCCUR';