export const LOGIN = 'LOGIN';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const GET_USER_INFO = 'GET_USER_INFO';
export const FETCHED_USER_INFO = 'FETCHED_USER_INFO';

export const GET_USER_PUBLICATIONS = 'GET_USER_PUBLICATIONS';
export const FETCHING_USER_PUBLICATIONS = 'FETCHING_USER_PUBLICATIONS';
export const FETCHED_USER_PUBLICATIONS = 'FETCHED_USER_PUBLICATIONS';
export const NO_MORE_USER_PUBLICATIONS = 'NO_MORE_USER_PUBLICATIONS';

export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const FETCHED_USER_FOLLOWERS = 'FETCHED_USER_FOLLOWERS';

export const GET_PARTNERS = 'GET_PARTNERS';
export const FETCHED_USER_PARTNERS = 'FETCHED_USER_PARTNERS';


export const PUBLISH_POST = 'PUBLISH_POST';

export const ERROR_OCCUR = 'ERROR_OCCUR';